### ISSUE TITLE
User can change the active date

### ISSUE THREAD

**Issue by dvenkatr** [nilenso/time-tracker#101]
- user can use "forward" / "back" button to change date by one day
- user can directly enter the date using a datepicker to go straight to a specific day

When either of the two above behaviours occur, a list of timers for that date becomes visible. Then the user can edit/start/stop any of that day's timers or create a new timer for that day.

**Comment by trycatcher** [comment]
@kirang89 PR is https://github.com/nilenso/time-tracker-web-nxt/pull/24
