### ISSUE TITLE
Set up Cljs environment.

### ISSUE THREAD

**Issue by dvenkatr** [nilenso/time-tracker#104]

**Comment by trycatcher** [comment]
Ideas on a ClJs boilerplate https://medium.com/@roman01la/how-to-create-clojurescript-app-4e38778c4762

**Comment by trycatcher** [comment]
Definition of done would include:-
1> A new Cljs frontend repo e.g. time-tracker-web-next
2> Scaffolding - 
-> A project structure
-> Dependencies to use (Reagent, Reframe)
-> Production builds
-> Separation of dev and product envs/dependencies/builds
-> Tests and CI (CircleCI integration)
-> Editor and IDE support

------ We test the above with a "Hello world" and then
------ look at next business features to determine if we need anything more

-> Documentation for on-boarding (once done we would want to move it to the Backend README)
-> Automate the setup as much as possible (optional?)

**Comment by kirang89** [comment]
CI and Automation will be deferred until appropriate.

**Comment by trycatcher** [comment]
Setup done with the following left (we should tackle them as separate issues):-
1. Cider-jack-in-cljs support
2. Running tests with "lein doo" on CircleCI. (We should broaden the scope of this to explore testing for the FE anyway and how to run the same in Circle)
