### ISSUE TITLE
Timers should always be created for the project name selected in the dropdown

### ISSUE THREAD

**Issue by jysandy** [nilenso/time-tracker#128]
Timers are often being created for the same project despite selecting a different project name.
<img width="542" alt="screen shot 2017-10-05 at 11 25 24 am" src="https://user-images.githubusercontent.com/8731801/31213693-80aa584c-a9c5-11e7-8287-738b163c1cee.png">
<img width="1365" alt="screen shot 2017-10-05 at 11 25 43 am" src="https://user-images.githubusercontent.com/8731801/31213694-80aef1ea-a9c5-11e7-9bef-3e005c51e670.png">

**Comment by trycatcher** [comment]
Closed with https://github.com/nilenso/time-tracker-web-nxt/commit/3c0718d954bbbc118f719f765cc300b4b25e254e
