### ISSUE TITLE
Build CRUD system for projects

### ISSUE THREAD

**Issue by jysandy** [nilenso/time-tracker#3]
A user's timer is associated with a project. The projects may be in a single level or in a hierarchy. The hierarchy could be just two or three projects deep or of infinite depth -- we still need to figure out which works best. Ex:
Community
|_ Open source development
....|_ Time tracker
........|_ <timer>

**Comment by neenaoffline** [comment]
I think we should start off with doing infinitely nestable hierarchies. Just so we don't have to revisit this chunk of work again.

**Comment by jysandy** [comment]
We'll need to figure out:
* Database schema -- although this issue is related to projects only, this might be a good time to start thinking about the schema for the service as a whole
* Authorization/permissions -- we may need object-level permissions
* Migrations -- will probably use [ragtime](https://github.com/weavejester/ragtime/) for this. Again, not strictly related to projects but now's a good time to think about it

**Comment by jysandy** [comment]
Set up schema and migrations in #5.
