### ISSUE TITLE
Admin should be able to mark an invoice as paid

### ISSUE THREAD

**Issue by dvenkatr** [nilenso/time-tracker#30]

**Comment by trycatcher** [comment]
@jysandy 
The PRs involved are
https://github.com/nilenso/time-tracker/pull/95
https://github.com/nilenso/time-tracker-web/pull/18

**Comment by trycatcher** [comment]
@jysandy 
Review changes incorporated.

**Comment by trycatcher** [comment]
Changes reviewed and merged, so closing
