### ISSUE TITLE
As an admin, I want to view a list of invoices that were saved in the past

### ISSUE THREAD

**Issue by dvenkatr** [nilenso/time-tracker#31]
They should reflect historical data (project assignment, rate, etc) captured at a point in the past

**Comment by trycatcher** [comment]
This will involve
1> Persisting invoices (at the moment, Admin ensures that only billable invoices are chosen)
2> Making invoices available through a list view for Admin to act on them

**Comment by trycatcher** [comment]
The PRs involved are
https://github.com/nilenso/time-tracker/pull/93
https://github.com/nilenso/time-tracker-web/pull/17

**Comment by trycatcher** [comment]
The PRs involved have been approved and merged (incorporating review comments).
