### ISSUE TITLE
Invoice should have entries only for people who have logged time against that client

### ISSUE THREAD

**Issue by jysandy** [nilenso/time-tracker#60]

**Comment by jysandy** [comment]
@dvenkatr @trycatcher while this may be an acceptable solution for now, note that in the future you may want to 'staff' people on a client, and when generating the invoice for that client, it should pick up only the hours logged by the people staffed on the client.

**Comment by jysandy** [comment]
The pull request for this feature is here: https://github.com/nilenso/time-tracker/pull/83

**Comment by trycatcher** [comment]
@jysandy Merged https://github.com/nilenso/time-tracker/pull/83 after merging the fix-ci into master. But this broke some Invoice functional tests. Missed them as that time all failures were getting masked by the cI failure. Have fixed them in the PR https://github.com/nilenso/time-tracker/pull/91
