### ISSUE TITLE
Invoice creation should use dates entered by the User

### ISSUE THREAD

**Issue by dvenkatr** [nilenso/time-tracker#80]
Start/end dates default to current date when the page is loaded. However if the User edits these dates those are not used when the Invoice is generated. Downloaded Invoice still shows the default dates. User-provided start/end dates are not taken into account. 
Note:- This only happens when User edits the date manually. It works fine if the "Back/Forward" buttons are used instead.

**Comment by jysandy** [comment]
@dvenkatr @trycatcher I don't understand this. Can you elaborate? What is the expected behaviour, and what is it that you actually see?

**Comment by trycatcher** [comment]
@jysandy When the user edits the start/end dates, they don't take effect. The invoice printed comes up with the start/end default i.e. current date. It only takes effect when the "Change Date" button is used

**Comment by jysandy** [comment]
Thanks, that makes much more sense.

**Comment by trycatcher** [comment]
@jysandy @dvenkatr Edited Title and added a description to make things easier to understand.

**Comment by trycatcher** [comment]
@jysandy @dvenkatr This has been merged. Closing this.
