### ISSUE TITLE
As an admin/user, I want to save an invoice that I have generated.

### ISSUE THREAD

**Issue by dvenkatr** [nilenso/time-tracker#86]

**Comment by trycatcher** [comment]
This is about saving the Invoice in DB and then generating a PDF of it (as before).
PRs are 
https://github.com/nilenso/time-tracker/pull/92
https://github.com/nilenso/time-tracker-web/pull/16

**Comment by trycatcher** [comment]
These have been merged. However we need to document the decision of storing staffing details (user, rate, hours) and tax details as strings in the DB (for now) over a normalized schema as an Architectural Trade-off somewhere (perhaps the ChangeLog for the next release which includes this?)
