### ISSUE TITLE
User / admin should be able to mark an invoice as "unusable".

### ISSUE THREAD

**Issue by dvenkatr** [nilenso/time-tracker#87]
An 'Unusable Invoice' in this context is one which is 'Unpaid' but we don't want to follow that up.
This implies that a 'Mark unusable' button only appears when the Invoice is unpaid.

**Comment by kirang89** [comment]
Fixed with:
- Backend: #97 
- Frontend: https://github.com/nilenso/time-tracker-web/pull/19
