### ISSUE TITLE
User should be able to view a well-formatted invoice.

### ISSUE THREAD

**Issue by dvenkatr** [nilenso/time-tracker#94]
- nilenso logo

- full name: 
`Nilenso Software LLP` in bold

- address:
#105, 10th Cross, 
Indiranagar I Stage,
Bangalore - 560038
GSTIN: 29AAKFN2903R1ZM

- `client name` in bold
- client address

- subtotals, totals and taxes right aligned
- `Total` and `value` in bold
- numbers formatted as INR 200,00

- `Notes` in bold

**Comment by trycatcher** [comment]
We should also have the Nilenso GST Id in the invoice

**Comment by kirang89** [comment]
We will do a DB migration to add a new column to the invoices table - `invoice-id`
This will enable us to allow changes to the invoice while retaining the older copies in the table.

So whenever a user would edit an invoice the existing copy would be marked as unusable and a new copy created with the edited changes

**Comment by trycatcher** [comment]
Should this migration be part of this story? And not a part of a separate "Edit Invoice" story when that happens?

**Comment by kirang89** [comment]
That makes sense. We'll drop this change for now and create a separate story for this when needed.
