### ISSUE TITLE
User should be able to stop a timer.

### ISSUE THREAD

**Issue by dvenkatr** [nilenso/time-tracker#99]

**Comment by kirang89** [comment]
Notes
--------

What we think the component hierarchy should look like:
- TimerPage > NewTimer, TimerList > Timer(mainly for display) > Duration

**Comment by trycatcher** [comment]
1. Timer page supports adding new timers and displays already set up timers
2. Persist timers in the DB, and displays already persisted timers
3. Make sure all relevant information is captured as part of timer (Notes, Project info etc)
4. Animation/ Progress bar while a timer runs
5. Any domain restrictions (e.g. should User be able to run multiple timers at the same time?)

**Comment by trycatcher** [comment]
@yudistrange Here's the PR for the work we did today https://github.com/nilenso/time-tracker-web-next/tree/log-time-redo

**Comment by trycatcher** [comment]
The new repo using Reframe and Reagent is at https://github.com/nilenso/time-tracker-web-nxt

**Comment by trycatcher** [comment]
@kirang89 PR herehttps://github.com/nilenso/time-tracker-web-nxt/pull/17, would you do a once-over quick review and merge?

**Comment by trycatcher** [comment]
Merged, closing
